[package]
name = "ems-model"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Model structs for Energy Modeling"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
utoipa = "4.0"
ts-rs = { version = "10.1", features = ["serde-compat", "chrono-impl"] }
