// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Factory = { 
/**
 * The name of the factory.
 */
name: string, 
/**
 * The id of the factory.
 */
id: string, 
/**
 * The location of the factory.
 */
location: string, 
/**
 * The lines of the factory.
 */
lines: Array<string>, };
