// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A production line that models dependencies between steps as a directed acyclic graph (DAG).
 */
export type Line = { 
/**
 * The name of the line.
 */
name: string, 
/**
 * The id of the line.
 */
id: string, 
/**
 * The dependency graph nodes.
 */
nodes: { [key in string]?: LineNode }, };

/**
 * Represents a node in the production line graph.
 */
export type LineNode = { 
/**
 * The id of the node.
 */
id: string, 
/**
 * The name of the node.
 */
name: string, 
/**
 * The step ID.
 */
step_id: string, 
/**
 * The steps that this step depends on (prerequisites).
 */
dependencies: Array<string>, 
/**
 * The steps that depend on this step.
 */
dependents: Array<string>, };
