// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Specialization } from "./worker";

/**
 * How can a machine be controlled?
 * does it need to be controlled by a human or can it be controlled by a computer?
 */
export type MachineControl = "Human" | "Computer";

/**
 * A machine in the factory.
 *
 * for the ems it is important how flexible the machine is in terms of how it can be turned on and off,
 * for how long a run is, and how much electricity it consumes.
 */
export type Step = { id: string, 
/**
 * The type of the step.
 */
step_type: StepType, 
/**
 * The name of the machine/task.
 */
name: string, 
/**
 * The power consumption of the machine.
 */
power_consumption: number, 
/**
 * The runtime of the machine in minutes.
 */
runtime_minutes: number, 
/**
 * the control of the machine
 */
control: MachineControl, 
/**
 * required specialization of the worker
 */
required_specialization: Specialization | null, };

export type StepType = "Machine" | "Task";
