// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simple weekly schedule
 */
export type Schedule = { weekly_shifts: { [key in WeekDay]?: WorkShift }, };

/**
 * What can a worker do?
 */
export type Specialization = { "Custom": string } | "CncMachineOperator";

/**
 * Represents a time of day in 24-hour format
 */
export type Time = { hour: number, minute: number, };

/**
 * Days of the week
 */
export type WeekDay = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";

/**
 * Represents a work shift with start and end times
 */
export type WorkShift = { start: Time, end: Time, };

export type Worker = { id: string, name: string, specialization: Array<Specialization>, schedule: Schedule, };
